server:
  port: 8000
eureka:
  instance:
    hostname: 7dwd7.com
#    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.application.name}:${server.port}
#    non-secure-port-enabled: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 3000


spring:
  application:
    name: eureka-server
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    root: info
  file: logs/${spring.application.name}.log

