server:
  port: 8080
spring:
  application:
    name: service-session-zuul
#网关: 网关超时配置,路由配置
zuul:
  ignoredServices: '*' #忽略所有未配置的service
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
#    redis-session-service:
#      path: /user-session/**
#      serviceId: service-session-redis
#      sensitiveHeaders: "*"##不传递
#      ignoredHeaders: "*" ##会传递
#路由: 测试客户端-1
    client1:
       sensitiveHeaders: "*"
       path: /client1/**
       service-id: client1
       strip-prefix: true
#       custom-sensitive-headers: true
#路由:  认证中心
    auth-center:
       sensitiveHeaders: "*"
       path: /auth/**
       service-id: auth-center
       strip-prefix: true

#负载:  ribbon负载均衡参数配置
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

#注册:
eureka:
  instance:
    hostname: 7dwd7.com
#    prefer-ip-address: true

    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.application.name}:${server.port}

  client:
    serviceUrl:
      defaultZone: http://7dwd7.com:8000/eureka/